name: build&push

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          push: true
          tags: aoxijy/netflow:latest

      # 添加 Telegram 通知步骤
      - name: Send Telegram Notification
        if: always() # 无论任务成功还是失败都会执行
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          STATUS="unknown"
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="✅ SUCCESS"
          elif [ "${{ job.status }}" == "failure" ]; then
            STATUS="❌ FAILURE"
          fi

          MESSAGE="GitHub Actions Job: *${{ github.workflow }}*\nStatus: *${STATUS}*\nRepository: *${{ github.repository }}*\nBranch: *${{ github.ref_name }}*\nCommit: *${{ github.sha }}*"

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="$MESSAGE" \
            -d parse_mode="Markdown"

